# Generated by Django 5.2.5 on 2026-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_inspection_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
