# Generated by Django 5.2 on 2026-10-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(max_length=10)),
                ("rule_name", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("UNDETERMINED", "Undetermined"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField()),
                ("evaluated_value", models.JSONField(blank=True, null=True)),
                ("expected_condition", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="leases.lease",
                    ),
                ),
            ],
        ),
    ]
