# Generated by Django 5.2 on 2026-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationresult",
            name="is_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="overridden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="overridden_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
