# Generated by Django 5.2 on 2026-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_validationresult_is_overridden_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("number_compare", "Field compared to a number"),
                            ("field_compare", "Field compared to another field"),
                            ("required_field", "Field must be present"),
                            ("date_order", "Date must be after another date"),
                            ("text_check", "Text must / must not contain words"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("operator", models.CharField(blank=True, max_length=20)),
                ("compare_field", models.CharField(blank=True, max_length=100)),
                ("number_value", models.FloatField(blank=True, null=True)),
                ("factor", models.FloatField(default=1.0)),
                ("text_value", models.CharField(blank=True, max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
