# Generated by Django 5.2 on 2026-10-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0003_customrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrule",
            name="template",
            field=models.CharField(
                choices=[
                    ("number_compare", "Field compared to a number"),
                    ("field_compare", "Field compared to another field"),
                    ("required_field", "Field must be present"),
                    ("date_order", "Date must be after another date"),
                    ("text_check", "Text must / must not contain words"),
                    ("term_length", "Lease term length (months) compared to a number"),
                    ("allowed_values", "Field must be one of a list of values"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RuleProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("source_quote", models.TextField(blank=True)),
                ("source_page", models.IntegerField(blank=True, null=True)),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("rule_update", "Update a built-in rule"),
                            ("custom_rule", "New custom rule"),
                            ("needs_developer", "Needs a developer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("confidence", models.FloatField(default=0.0)),
                ("target_rule_id", models.CharField(blank=True, max_length=10)),
                ("config_changes", models.JSONField(blank=True, null=True)),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("number_compare", "Field compared to a number"),
                            ("field_compare", "Field compared to another field"),
                            ("required_field", "Field must be present"),
                            ("date_order", "Date must be after another date"),
                            ("text_check", "Text must / must not contain words"),
                            (
                                "term_length",
                                "Lease term length (months) compared to a number",
                            ),
                            ("allowed_values", "Field must be one of a list of values"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("operator", models.CharField(blank=True, max_length=20)),
                ("compare_field", models.CharField(blank=True, max_length=100)),
                ("number_value", models.FloatField(blank=True, null=True)),
                ("factor", models.FloatField(default=1.0)),
                ("text_value", models.CharField(blank=True, max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="validation.customrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
