# Generated by Django 5.2 on 2026-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0004_alter_customrule_template_ruleproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrule",
            name="template",
            field=models.CharField(
                choices=[
                    ("number_compare", "Field compared to a number"),
                    ("field_compare", "Field compared to another field"),
                    ("required_field", "Field must be present"),
                    ("date_order", "Date must be after another date"),
                    ("text_check", "Text must / must not contain words"),
                    ("term_length", "Lease term length (months) compared to a number"),
                    ("allowed_values", "Field must be one of a list of values"),
                    ("manual_check", "Manual check — a human verifies on every lease"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ruleproposal",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("number_compare", "Field compared to a number"),
                    ("field_compare", "Field compared to another field"),
                    ("required_field", "Field must be present"),
                    ("date_order", "Date must be after another date"),
                    ("text_check", "Text must / must not contain words"),
                    ("term_length", "Lease term length (months) compared to a number"),
                    ("allowed_values", "Field must be one of a list of values"),
                    ("manual_check", "Manual check — a human verifies on every lease"),
                ],
                max_length=20,
            ),
        ),
    ]
