# Generated by Django 5.2 on 2026-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0005_alter_customrule_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrule",
            name="field_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
