# Generated by Django 5.2 on 2026-10-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(blank=True, max_length=255)),
                ("landlord_name", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "rent_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("rent_frequency", models.CharField(blank=True, max_length=20)),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "annual_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("escalation_clause", models.TextField(blank=True)),
                ("renewal_terms", models.TextField(blank=True)),
                ("termination_terms", models.TextField(blank=True)),
                ("extracted_unit_id", models.CharField(blank=True, max_length=100)),
                ("document", models.FileField(upload_to="leases/documents/")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("provider_used", models.CharField(blank=True, max_length=50)),
                ("processing_error", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leases",
                        to="units.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaseClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clause_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("raw_text", models.TextField()),
                ("interpretation", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit document statement"),
                            ("interpreted", "AI interpretation"),
                            ("inferred", "Inferred from context"),
                        ],
                        default="explicit",
                        max_length=20,
                    ),
                ),
                ("source_page", models.IntegerField(blank=True, null=True)),
                ("source_text", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("is_unusual", models.BooleanField(default=False)),
                ("unusual_reason", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_correction", "Needs Correction"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="leases.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaseFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_type", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("related_fields", models.JSONField(default=list)),
                ("source_reference", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reviewer_comment", models.TextField(blank=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="leases.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaseField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("extracted_value", models.JSONField()),
                ("normalized_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("source_page", models.IntegerField(blank=True, null=True)),
                ("source_text", models.TextField(blank=True)),
                ("source_location", models.JSONField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_correction", "Needs Correction"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_value", models.JSONField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "unique_together": {("lease", "field_name")},
            },
        ),
    ]
