# Generated by Django 5.2 on 2026-10-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasefield",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leasefield",
            name="contradiction_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leasefield",
            name="data_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="leasefield",
            name="display_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="leasefield",
            name="extraction_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leasefield",
            name="has_contradiction",
            field=models.BooleanField(default=False),
        ),
    ]
