# Generated by Django 5.2 on 2026-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.BigIntegerField()),
                ("action", models.CharField(max_length=100)),
                ("actor", models.CharField(max_length=255)),
                ("previous_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__0bff9a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_ee9c56_idx"
                    ),
                ],
            },
        ),
    ]
