# Generated by Django 5.2 on 2026-10-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_unit_id", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("unit_type", models.CharField(max_length=20)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("parking_bay", models.CharField(blank=True, max_length=20)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                            ("archived", "Archived"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="properties.building",
                    ),
                ),
            ],
        ),
    ]
